-- Active: 1697386701896@@127.0.0.1@3306@practiceQuestions

--CREATE TABLE
CREATE TABLE CUSTOMERS (
    ID INT NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    AGE INT NOT NULL,
    ADDRESS CHAR(25),
    SALARY DECIMAL(18, 2),
    PRIMARY KEY (ID)
);

--Description of the Table
DESC CUSTOMERS;

--SQL CREATE TABLE IF NOT EXISTS
CREATE TABLE IF NOT EXISTS CUSTOMERS (
    ID INT NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    AGE INT NOT NULL,
    ADDRESS CHAR(25),
    SALARY DECIMAL(18, 2),
    PRIMARY KEY (ID)
);

--Creating a Table from an Existing Table
CREATE TABLE SALARY AS
SELECT ID, SALARY FROM CUSTOMERS;

DESC SALARY;

--INSERT
INSERT INTO CUSTOMERS VALUES
(1, 'Ramesh', 32, 'Ahmedabad', 2000.00),
(2, 'Khilan', 25, 'Delhi', 1500.00 ),
(3, 'Kaushik', 23, 'Kota', 2000.00 ),
(4, 'Chaitali', 25, 'Mumbai', 6500.00 ),
(5, 'Hardik', 27, 'Bhopal', 8500.00 ),
(6, 'Komal', 22, 'Hyderabad', 4500.00 ),
(7, 'Muffy', 24, 'Indore', 10000.00 );

SELECT * FROM `CUSTOMERS`;

--RENAME
RENAME TABLE CUSTOMERS TO BUYERS;

SELECT * FROM BUYERS;

ALTER TABLE BUYERS RENAME TO CUSTOMERS;

SELECT * FROM CUSTOMERS;






--ALTER TABLE − ADD Column
ALTER TABLE CUSTOMERS ADD SEX CHAR(1);

SELECT * FROM CUSTOMERS;

--ALTER TABLE − DROP COLUMN
ALTER TABLE CUSTOMERS DROP COLUMN SEX;

SELECT * FROM CUSTOMERS;

--ALTER TABLE − MODIFY DATATYPE
ALTER TABLE CUSTOMERS MODIFY COLUMN ID DECIMAL(18, 4);
SELECT * FROM CUSTOMERS;

ALTER TABLE CUSTOMERS MODIFY COLUMN ID INT;
SELECT * FROM `CUSTOMERS`;


--SELECT
SELECT 10*10

SELECT 10%10

SELECT CONCAT(NAME, ' ', AGE) AS DETAILS, ADDRESS
FROM CUSTOMERS ORDER BY `NAME`;